
site_name: FusionData Ecosystem
repo_name: 'fusioninsight/ecosystem'
repo_url: 'https://github.com/fusioninsight/ecosystem/tree/en'

theme:
  name: 'material'
  language: 'en'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  feature:
    tabs: false

nav:
- Business Intelligence:
  - QlikView:
    - 12 <--> C60: Business_Intelligence/QlikView.md
    - 12 <--> C70: Business_Intelligence/QlikView.md
    - 12 <--> C80: Business_Intelligence/QlikView.md
  - Tableau:
    - 10.0.0 <--> C50: Business_Intelligence/Tableau.md
    - 10.1.4 <--> C60: Business_Intelligence/Tableau.md
    - 10.3.2 <--> C70: Business_Intelligence/Tableau.md
    - 10.5.0 <--> C80: Business_Intelligence/Tableau.md
- Data Analysis:
  - Rapidminer Studio:
    - 8.2.001 <--> C80: Data_Analysis/RapidMiner.md
- Data Integration:
  - Apache NiFi:
    - 1.7.1 <--> C80: Data_Integration/Apache_NiFi.md
  - Informatica PowerCenter:
    - 10.2.0 <--> 6.5: Data_Integration/Informatica_PowerCenter.md
  - Informatica PowerexChange CDC:
    - 10.2.0 <--> 6.5: Data_Integration/Informatica_PWX_CDC.md
  - Talend:
    - 6.4.1 <--> C80: Data_Integration/Talend.md
    - 7.0.1 <--> C80: Data_Integration/Talend.md

extra:
  social:
    - type: github
      link: https://github.com/fusioninsight
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/jq.js'
  - 'js/extra.js'
  - 'js/baidu-tongji.js'

extra_css:
  - 'css/extra.css'
