site_name: 智能数据生态地图
repo_name: 'fusioninsight/ecosystem'
repo_url: 'https://github.com/fusioninsight/ecosystem/tree/zh-hans'

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  feature:
    tabs: false

nav:
- 数据可视化:
  - 对接Tableau: Business_Intelligence/Tableau.md
  - 对接QlikView: Business_Intelligence/QlikView.md
  - 对接Oracle BIEE: Business_Intelligence/Oracle_BIEE.md
- 数据分析:
  - 对接Alteryx: Data_Analysis/Alteryx.md
  - 对接RapidMiner: Data_Analysis/RapidMiner.md
  - 对接Splunk: Data_Analysis/Splunk.md
- 数据集成:
  - 对接IBM InfoSphere DataStage: Data_Integration/IBM_InfoSphere_DataStage.md
  - 对接Informatica PowerCenter: Data_Integration/Informatica_PowerCenter.md
  - 对接Informatica PWX CDC: Data_Integration/Informatica_PWX_CDC.md
  - 对接Oracle GoldenGate: Data_Integration/Oracle_GoldenGate.md
  - 对接Talend: Data_Integration/Talend.md
  - 对接H2O.ai: Data_Integration/H2O.ai.md
  - 对接Kettle: Data_Integration/Kettle_6.1.md
  - 对接Apache NiFi: Data_Integration/Apache_NiFi.md
  - 对接Denodo: Data_Integration/Denodo.md
  - 对接TIBCO BW: Data_Integration/TIBCO_BusinessWorks.md
  - 对接Knime: Data_Integration/Knime.md
  - 对接Kafka-manager: Data_Integration/Kafka_Manager.md
- 集成开发环境:
  - 对接RStudio: Development/RStudio.md
  - 对接Apache Zeppelin:
    - Zeppelin0.7.2 <--> C60: Development/Zeppelin_0.7.2.md
    - Zeppelin0.7.3 <--> C70: Development/Zeppelin_0.7.3.md
    - Zeppelin0.8.0 <--> C80: Development/Zeppelin_0.8.0.md
  - 对接Jypyter Notebook: Development/Jupyter_Notebook.md
  - 对接DBeaver: Development/DBeaver.md
  - 对接DbVisualizer: Development/DbVisualizer.md
  - 对接Squirrel: Development/Squirrel.md
- SQL引擎:
  - 对接Apache Kylin:
    - Kylin 1.6.0 <--> C60: SQL_Analytics/Apache_Kylin_1.6.0.md
    - Kylin 2.1.0 <--> C70: SQL_Analytics/Apache_Kylin_2.1.0.md
    - Kylin 2.3.1 <--> C80: SQL_Analytics/Apache_Kylin_2.3.1.md
    - Kylin 2.6.1 <--> 6.5: SQL_Analytics/Apache_Kylin_2.6.1.md
  - 对接Kyligence: SQL_Analytics/Kyligence.md
  - 对接Presto:
    - Presto0.146 <--> C60: SQL_Analytics/Presto_0.155.md
    - Presto0.184 <--> C70: SQL_Analytics/Presto_0.184.md
    - Presto0.210 <--> C80: SQL_Analytics/Presto_0.210.md
- 数据库: /#
- 其他:
  - 对接FUSE: Other/FUSE.md
  - 对接Gis-Tools-For-Hadoop: Other/GIS_Tools.md
  - 对接Apache Livy: Other/Apache_Livy.md
  - 对接Logstash: Other/Elasticsearch_Related.md
  - 对接Kibana: Other/Elasticsearch_Related.md
  - 对接elasticsearch-head: Other/Elasticsearch_Related.md
  - 对接beats: Other/Elasticsearch_Related.md

extra:
  social:
    - type: github
      link: https://github.com/fusioninsight
  search:
    language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/jq.js'
  - 'js/extra.js'
  - 'js/baidu-tongji.js'

extra_css:
  - 'css/extra.css'
